[programs.localnet]
token = "YourProgramAddress"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "cargo test-bpf"

